### ISSUE TITLE
any incompatibility between pyrosm and papermill?

### ISSUE THREAD

**Issue by PatGendre** [HTenkanen/pyrosm#120]
Hi, thanks for this great software:-)    
I a run a python 3.8 notebook which uses the pyrosm library for reading pbf files. The notebook runs smoothly on jyputer-lab but fails when executed by papermill on a docker container. 

The error is 
```
  File "/usr/local/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
AssertionError: 

```
The instruction is 
`osm=pyrosm.OSM(SOURCE_DIR+"/"+PBF_FILE)`

Note also than when executed with python 3.9 (not tested yet with 3.8), I see the following exception:
```
python compute.py
/home/pdi/projects/open-mobility-indicators/work/load-osm/.venv/lib/python3.9/site-packages/geopandas/_compat.py:106: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.1-CAPI-1.14.2). Conversions between both will be slow.
  warnings.warn(
AssertionError
Exception ignored in: 'pyrosm_proto.BlobHeader._protobuf_deserialize'
Traceback (most recent call last):
  File "/home/pdi/projects/open-mobility-indicators/work/load-osm/.venv/lib/python3.9/site-packages/pyrosm/utils/__init__.py", line 155, in get_bounding_box
    msg.ParseFromString(f.read(msg_len))
```

I searched both in the pyrosm and in the papermill gihtub issues but did not find anything about this question,   
however maybe you are aware of any incompatibilities between papermill and pyrosm? thanks

**Comment by PatGendre** [comment]
Sorry I've found the reason of my problems and it was not a pyrosm neither a papermill issue (rather a data issue) !
