### ISSUE TITLE
SIGSEGV Error in fresh Conda and Basic Code

### ISSUE THREAD

**Issue by leohoy** [HTenkanen/pyrosm#161]
My Code:

```
from pyrosm import OSM
from pyrosm import get_data

fs = get_data('muenchen')
print(fs)
osm = OSM(fs)
print(osm)
natural = osm.get_natural()
print(natural)
```

The output:
```

/home/leo/miniconda3/envs/pyrosm/lib/python3.7/site-packages/geopandas/_compat.py:115: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string
/tmp/pyrosm/Muenchen.osm.pbf
<pyrosm.pyrosm.OSM object at 0x7f5df1d0c1d0>

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by HTenkanen** [comment]
@leohoy : Could you please provide more information about your system/setup? With this information it is not possible to say what might be causing this error. Sigsegv error can arise from various reasons.. 

- What OS are you using?
- What packages (and versions) do you have in your environment?
- Is geopandas working normally otherwise?

**Comment by leohoy** [comment]
Ah Geopandas is not working indeed. Error message:

```
/home/leo/miniconda3/envs/pyrosm/lib/python3.7/site-packages/geopandas/_compat.py:115: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: Failed to read GeoJSON data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leo/Leo/Arbeit/ImmoAPI/Python/PrepareData.py", line 5, in <module>
    gp.read_file('/home/leo/Leo/Arbeit/ImmoAPI/test.geojson')
  File "/home/leo/miniconda3/envs/pyrosm/lib/python3.7/site-packages/geopandas/io/file.py", line 201, in _read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/home/leo/miniconda3/envs/pyrosm/lib/python3.7/site-packages/fiona/env.py", line 408, in wrapper
    return f(*args, **kwargs)
  File "/home/leo/miniconda3/envs/pyrosm/lib/python3.7/site-packages/fiona/__init__.py", line 257, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/home/leo/miniconda3/envs/pyrosm/lib/python3.7/site-packages/fiona/collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 540, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: Failed to read GeoJSON data
```


I use Ubuntu Ubuntu 20.04.3 LTS 

I installed pyrosm as the first package in a fresh Conda environment with Python 3.7 with `conda install -c conda-forge pyrosm `. I did not install any other packages.

```
Package            Version
------------------ ---------
attrs              21.2.0
certifi            2021.10.8
click              8.0.3
click-plugins      1.1.1
cligj              0.7.2
cykhash            2.0.0
Cython             0.29.25
Fiona              1.8.20
geopandas          0.10.2
importlib-metadata 4.8.2
Jinja2             3.0.3
MarkupSafe         2.0.1
munch              2.5.0
numpy              1.21.4
pandas             1.3.4
pip                21.2.2
pygeos             0.12.0
pyproj             3.2.1
pyrobuf            0.9.3
pyrosm             0.6.1
python-dateutil    2.8.2
python-rapidjson   1.5
pytz               2021.3
setuptools         58.0.4
Shapely            1.8.0
six                1.16.0
typing_extensions  4.0.1
wheel              0.37.0
zipp               3.6.0
```

Yes, i am running this on my own computer

**Comment by leohoy** [comment]
So i got to run geopandas, but still I get the same SIGSEV error, when running the script..

**Comment by leohoy** [comment]
Solved it by reinstalling header files and static libraries: sudo apt-get install python3-dev

**Comment by HTenkanen** [comment]
@leohoy: Okay, great so I assume everything is working now? I'll close this now, but in case you have issues still, feel free to re-open.
