### ISSUE TITLE
Cykhas error when importing pyrosm

### ISSUE THREAD

**Issue by RobertEdwardes** [HTenkanen/pyrosm#164]
when importing pyrosm i get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyrosm\__init__.py", line 2, in <module>
    from pyrosm.pyrosm import OSM
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyrosm\pyrosm.py", line 3, in <module>
    from pyrosm.pbfreader import parse_osm_data
  File "pyrosm/pbfreader.pyx", line 1, in init pyrosm.pbfreader
    from pyrosm.exceptions import PBFNotImplemented
  File "pyrosm/data_filter.pyx", line 1, in init pyrosm.data_filter
    import numpy as np
TypeError: C function cykhash.khashsets.Int64Set_from_buffer has wrong signature (expected PyObject *(__Pyx_memviewslice, int __pyx_skip_dispatch, struct __pyx_opt_args_7cykhash_9khashsets_Int64Set_from_buffer *__pyx_optional_args), got struct __pyx_obj_7cykhash_9khashsets_Int64Set *(__Pyx_memviewslice, int __pyx_skip_dispatch, struct __pyx_opt_args_7cykhash_9khashsets_Int64Set_from_buffer *__pyx_optional_args))

**Comment by RobertEdwardes** [comment]
Already reported
