### ISSUE TITLE
Invalid geometries during handling of get_buildings()

### ISSUE THREAD

**Issue by Evelyn-M** [HTenkanen/pyrosm#44]
Dear Henrikki

First things first, thanks a lot for sharing this great and useful project!

Checking out your tutorials has worked fine for me, however I keep running into GEOSExceptions when trying to get building dataframes for bigger areas (e.g. "Helsinki" or "Zuerich"); apparently due to some issue with invalid geometries that some relations result in when constructing them from the data dump. 

Here's an output that reproduces the error; any idea on how to correct that would be very much appreciated!

```
fp_h = pyrosm.get_data("Helsinki", directory="/Users/user/Downloads")
osm_h = pyrosm.OSM(fp_h)
buildings_h = osm_h.get_buildings()
```
Returns
```
buildings_h = osm_h.get_buildings()
Traceback (most recent call last):

  File "<ipython-input-14-457334a3e0f2>", line 1, in <module>
    buildings_h = osm_h.get_buildings()

  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pyrosm/pyrosm.py", line 218, in get_buildings
    self.bounding_box

  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pyrosm/buildings.py", line 40, in get_building_data
    bounding_box)

  File "pyrosm\frames.pyx", line 68, in pyrosm.frames.prepare_geodataframe

  File "pyrosm\frames.pyx", line 78, in pyrosm.frames.prepare_geodataframe

  File "pyrosm\frames.pyx", line 57, in pyrosm.frames.prepare_relation_gdf

  File "pyrosm\relations.pyx", line 175, in pyrosm.relations.prepare_relations

  File "pyrosm\relations.pyx", line 176, in pyrosm.relations.prepare_relations

  File "pyrosm\relations.pyx", line 165, in pyrosm.relations._prepare_relations

  File "pyrosm\relations.pyx", line 134, in pyrosm.relations.get_relations

  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pygeos/predicates.py", line 258, in is_valid
    result = lib.is_valid(geometry, **kwargs)

GEOSException: IllegalArgumentException: Argument must be Polygonal or LinearRing
```
Thanks a lot,
cheers,

Evelyn

**Comment by HTenkanen** [comment]
Hi @Evelyn-M! And thanks a lot for reporting this. 🙏 I will take a look at it. Seems that checking for valid geometries is causing this.

**Comment by Evelyn-M** [comment]
I initially installed pyrosm via pip install in my working venv (on a mac), and also did a manual pip install for the 2 missing packages cykhash and pygeos.

Re-installing in a clean environment with `conda install -c conda-forge pyrosm` has worked for me, no geos exception anymore. 

```
geos 3.8.1
pyrobuf-0.9.3
cython-0.29.21 
python-rapidjson-0.9 
cykhash-1.0.2     
pygeos-0.7.1   
pyrosm-0.5.2   
```
Sorry for bothering!
