### ISSUE TITLE
Error: "ValueError: Provide at least 4 coordinates to create a linearring."

### ISSUE THREAD

**Issue by saifullah73** [HTenkanen/pyrosm#46]
### Description
I am trying to use pyrosm to parse my OSM data. However I am failing to run two important methods. Namely "get_buildings()" and "get_landuse()". Both return a similar error attached below. Please advice if something might be wrong at my end, or put it up as a reported bug if its something internal

### Code: 
from pyrosm import OSM
from pyrosm import get_data
fp = get_data("test_pbf")
osm = OSM(fp)
buildings = osm.get_buildings()
buildings.plot()

### Error:
/home/saifullah/anaconda3/envs/ox/bin/python /home/saifullah/Saif/FYP/Projects/covid19-preprocess/src/Parser-test.py
/home/saifullah/anaconda3/envs/ox/lib/python3.8/site-packages/pyrosm/buildings.py:21: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  nodes, ways, relation_ways, relations = get_osm_data(node_arrays=None,
Traceback (most recent call last):
  File "/home/saifullah/Saif/FYP/Projects/covid19-preprocess/src/Parser-test.py", line 6, in <module>
    buildings = osm.get_buildings()
  File "/home/saifullah/anaconda3/envs/ox/lib/python3.8/site-packages/pyrosm/pyrosm.py", line 213, in get_buildings
    gdf = get_building_data(self._node_coordinates,
  File "/home/saifullah/anaconda3/envs/ox/lib/python3.8/site-packages/pyrosm/buildings.py", line 38, in get_building_data
    gdf = prepare_geodataframe(nodes, node_coordinates, ways,
  File "pyrosm\frames.pyx", line 68, in pyrosm.frames.prepare_geodataframe
  File "pyrosm\frames.pyx", line 75, in pyrosm.frames.prepare_geodataframe
  File "pyrosm\frames.pyx", line 37, in pyrosm.frames.prepare_way_gdf
  File "pyrosm\geometry.pyx", line 360, in pyrosm.geometry.create_way_geometries
  File "pyrosm\geometry.pyx", line 349, in pyrosm.geometry._create_way_geometries
  File "pyrosm\geometry.pyx", line 318, in pyrosm.geometry.create_polygon_geometry
  File "pyrosm\geometry.pyx", line 309, in pyrosm.geometry.create_polygon_geometry
  File "/home/saifullah/anaconda3/envs/ox/lib/python3.8/site-packages/pygeos/decorators.py", line 55, in wrapped
    return func(*args, **kwargs)
  File "/home/saifullah/anaconda3/envs/ox/lib/python3.8/site-packages/pygeos/creation.py", line 88, in polygons
    shells = linearrings(shells)
  File "/home/saifullah/anaconda3/envs/ox/lib/python3.8/site-packages/pygeos/creation.py", line 72, in linearrings
    return _wrap_construct_ufunc(lib.linearrings, coords, y, z)
  File "/home/saifullah/anaconda3/envs/ox/lib/python3.8/site-packages/pygeos/creation.py", line 21, in _wrap_construct_ufunc
    return func(coords)
ValueError: Provide at least 4 coordinates to create a linearring.

**Comment by HTenkanen** [comment]
@saifullah73 Thanks for reporting this! 

Could you tell a bit more about your setup so that I could understand how to possibly replicate this issue:
- What operating system?
- How did you install the library? (using conda / pip / something else?) 
- What dataset are you using that produces the error? (or does it happen with any dataset?)

**Comment by saifullah73** [comment]
To answer your question in order.
1) My operating system is Ubuntu 18.04.5 LTS
2) I installed the library via pip (in my google colab environment) and using conda (locally in my machine). I get same error in both settings
3) I am using the test_pbf data provided internally by the library and also tried by downloading a dataset (fp = get_data("Aachen"))

Note: The error arrives with the datasets that I can either use directly or download via Pyrosm, It does not arise when I manually extract a osm.pbf file using osmconvert. In that case I am using Pakistan's osm data.

**Comment by HTenkanen** [comment]
@saifullah73 Okay, thanks for this info! I try to replicate the error with a similar setup to see if I can replicate this. 

By the way, could you check which version of `pygeos` library you have installed in your system as the error hints to that direction?

**Comment by saifullah73** [comment]
Sure, my pygeos is at version 0.8

**Comment by HTenkanen** [comment]
Okay there are probably some changes in new version of pygeos library that causes this. A quick fix for this issue is to downgrade your pygeos version to the last release, i.e pygeos==0.7.1. Haven't tested but probably should work

**Comment by HTenkanen** [comment]
@saifullah73 Okay, now this should be fixed in a new release v0.5.3 that you can install from PyPi with pip. Please go and try it out! If you get any further issues, don't hesitate to open this again. Cheers!

**Comment by saifullah73** [comment]
It work, thanks, could you also release it via Conda

**Comment by HTenkanen** [comment]
@saifullah73 Ok good to hear! And yes, I will release it via conda as well soon (when I find a few free moments).

**Comment by HTenkanen** [comment]
@saifullah73 FYI: Now also available from conda-forge
