### ISSUE TITLE
Failed to install pyrosm on Python3.7 OSX

### ISSUE THREAD

**Issue by bakwc** [HTenkanen/pyrosm#65]
```
$ sudo python3.7 -m pip install pyrosm
WARNING: The directory '/home/fippo/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyrosm
  Downloading pyrosm-0.5.3.tar.gz (2.0 MB)
     |████████████████████████████████| 2.0 MB 1.7 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-pa39_a85/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython cykhash pyrobuf
       cwd: None
  Complete output (58 lines):
  WARNING: The directory '/home/fippo/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  Collecting setuptools
    Downloading setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting wheel
    Downloading wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting Cython
    Downloading Cython-0.29.21-cp37-cp37m-manylinux1_x86_64.whl (2.0 MB)
  Collecting cykhash
    Downloading cykhash-1.0.2.tar.gz (26 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting pyrobuf
    Downloading pyrobuf-0.9.3.tar.gz (258 kB)
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4yhaa6ai/pyrobuf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4yhaa6ai/pyrobuf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4yhaa6ai/pyrobuf/pip-egg-info
           cwd: /tmp/pip-install-4yhaa6ai/pyrobuf/
      Complete output (33 lines):
      WARNING: The directory '/home/fippo/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
      rendering 'pyrobuf_list.pyx' from '/tmp/pip-install-4yhaa6ai/pyrobuf/pyrobuf/protobuf/templates/pyrobuf_list_pyx.tmpl'
      rendering 'pyrobuf_list.pxd' from '/tmp/pip-install-4yhaa6ai/pyrobuf/pyrobuf/protobuf/templates/pyrobuf_list_pxd.tmpl'
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-4yhaa6ai/pyrobuf/setup.py", line 158, in <module>
          zip_safe=False,
        File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 144, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/tmp/pip-install-4yhaa6ai/pyrobuf/setup.py", line 72, in run_commands
          self.ext_modules.extend(self.pyrobufize_builtins())
        File "/tmp/pip-install-4yhaa6ai/pyrobuf/setup.py", line 135, in pyrobufize_builtins
          include_path=['pyrobuf/src'])
        File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 749, in cythonize
          ctx = c_options.create_context()
        File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 577, in create_context
          self.cplus, self.language_level, options=self)
        File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 75, in __init__
          from . import Builtin, CythonScope
        File "/usr/lib/python3/dist-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
          from .UtilityCode import CythonUtilityCode
        File "/usr/lib/python3/dist-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
          from .TreeFragment import parse_from_strings, StringParseContext
        File "/usr/lib/python3/dist-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
          from .Visitor import VisitorTransform
        File "/usr/lib/python3/dist-packages/Cython/Compiler/Visitor.py", line 15, in <module>
          from . import ExprNodes
        File "/usr/lib/python3/dist-packages/Cython/Compiler/ExprNodes.py", line 2713
          await = None
                ^
      SyntaxError: invalid syntax
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 20.0.2; however, version 20.2.4 is available.
  You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 /usr/local/lib/python3.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-pa39_a85/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython cykhash pyrobuf Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.
```

**Comment by bakwc** [comment]
I was using old version of cython. Upgrading cythin helped:
```
sudo python3.7 -m pip install cython --upgrade --ignore-installed
```
